name: Deploy Blazor Server to Render

on:
  push:
    branches:
      - main # Altere para sua branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0" # Altere conforme a versão do seu projeto

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar e publicar a aplicação
        run: dotnet publish -c Release -o out

      - name: Deploy no Render
        run: |
          curl -X POST "https://api.render.com/v1/services/srv-cudpvjogph6c73fg1ssg/deploys" \
          -H "Authorization: Bearer rnd_ruGXV9YUasiIVIkX4GV2luNl1xji" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -d '{}'
